### ISSUE TITLE
Wallet Desktop Mina Problem

### ISSUE THREAD

**Issue by roomit-xyz** [nerdvibe/clorio-client#80] opened 2022-09-22 16:56 UTC
Hallo Team,

I used clorio desktop version in my arch linux. when application running, I have only blank page (white page) and not resolved. But for windows manager loaded very well. Any suggestion for this issue?

Best Regards
Dwiyan

**Comment by nerdvibe** [comment] 2023-02-22 12:46
Closing as duplicate of #83

**Closed by nerdvibe** 2023-02-22 12:46 UTC
